Mute Forums, Help, Various Fixes
jocosocial/swiftarr pull request #104
Opened 2022-12-17 04:55 UTC by cohoe

Big Stuff
* https://github.com/jocosocial/swiftarr/issues/39 New feature for a user to "mute" a forum. This sets a flag on the forum that tells the UI to push it out of the top of any forum lists. API response order is not changed so clients are responsible for implementing the sort. New API calls are added for a user to see all of their muted forums.
* Related to the mutes feature, the first real backwards-compatible database migration.
* Added help button and text to forums and events.

Little Stuff
* Fix bug with ambiguous column name in API calls for forums favorites.
* https://github.com/jocosocial/swiftarr/issues/103 Fix bug in API call preventing favorited forum posts from being seen in the favorited posts view.
* Consistent trailing punctuation in forum category descriptions.

2023-01-16 23:31 UTC, challfry requested changes
Not all of this stuff is actionable; some of it is just comments. But, I'd need some convincing to keep the muting sort order as it is. I also suggested changes to the image overlay that I think improve it but could be talked out of.

2023-01-16 23:31 UTC, challfry commented on Sources/App/Controllers/Structs/ControllerStructs.swift
> +	/// If this forum is for an Event on the schedule, the ID of the event.
I'm not sure about putting the eventID in the API in this way, as it means we've got to do joins on the Event table for lots of searches. More specifically it means that it'll be hard to optimize those joins away without breaking the API. A different possibility is that we add a call to the EventManager that takes a forum ID and returns the linked Event. We'd still need to know whether a Forum had an associated Event, but that's a bool and much easier to optimize. 

And yes, the Event DTO has a ForumID field; if I was thinking I would have gotten rid of that before 1.0 and added a forumForEvent() route to the ForumController. At least that direction doesn't include extra joins.

2023-01-16 23:31 UTC, challfry commented on Sources/App/Resources/Views/moderation/fezPostView.html
> +												<span title="#localTime(modData.fezPost.timestamp)" class="text-muted">#relativeTime(modData.fezPost.timestamp)</span>
Groovy.

2023-01-17 21:53 UTC, cohoe commented on Sources/App/Pivots/ForumReaders.swift
> +			.field("mute", .bool, .required)
Yeah I wasn't super sure what was the best approach here. Making the field creation only part of the update migration is fine. Should I keep the `do/catch` logic to detect the failure? Or is this now redundant since the migration would not even run on any future attempt?

2023-01-17 22:04 UTC, cohoe commented on Sources/App/Resources/Views/imageOverlay.html
> +	<div class="modal-content">
Yeah that's fine. Though this breaks on desktop view. I'll hack up the CSS a bit to make it work on both.

2023-01-17 22:04 UTC, cohoe commented on Sources/App/Resources/Views/admin/serversettings.html
> +						<input type="number" id="maxAlternateAccounts" name="maxAlternateAccounts" min="0" max="40" value="#(settings.maxAlternateAccounts)" #if(trunk.username != "admin"):disabled#endif>
SGTM

2023-01-17 22:07 UTC, cohoe commented on Sources/App/Site/SiteEventsController.swift
> +	/// `GET /events/:event_id`
No problem

2023-01-17 22:10 UTC, cohoe commented on Sources/App/Site/SiteForumController.swift
> +				var mutedForums: [ForumListData] = []
I'm OK with that. I had a thought the other day of "what happens if a user mutes 50+ forums" that I didn't expand on, and I think that would also interact poorly with the pagination as currently written. And yeah if we're gonna add pinned forums modifying the search sort criteria a bit pre-pagination seems fine to me.

2023-01-17 22:13 UTC, cohoe commented on Sources/App/Controllers/Structs/ControllerStructs.swift
> +	/// If this forum is for an Event on the schedule, the ID of the event.
I may suspend this particular feature until we can talk about it more. Sounds like maybe the whole pattern could change.

2023-01-19 19:22 UTC, cohoe commented on Sources/App/Site/SiteForumController.swift
> +				var mutedForums: [ForumListData] = []
I've implemented your commit. We should probably do the same thing to favorites too (nil vs false) for consistency. Some Day(tm).

2023-01-19 21:02 UTC, cohoe commented on Sources/App/Controllers/Structs/ControllerStructs.swift
> +	/// If this forum is for an Event on the schedule, the ID of the event.
We're already joining the forums `scheduleEvent` in https://github.com/jocosocial/swiftarr/blob/1d0017e0092af8827085014e6b41ce7819f2811b/Sources/App/Controllers/ForumController.swift#L233 to show the events time in the blue text in search results and event categories. Since we already have that data adding the event ID for these cases feels pretty trivial. Those use `buildForumListData()` (https://github.com/jocosocial/swiftarr/blob/master/Sources/App/Controllers/ForumController.swift#L1115) which expects that the event data may not be present. The only new case of a query is in `buildForumData()` (https://github.com/jocosocial/swiftarr/blob/1d0017e0092af8827085014e6b41ce7819f2811b/Sources/App/Controllers/ForumController.swift#L1144) which I added in my PR. I just added a new gate to only perform the query if the forum is in an event category. Since this is done only once when viewing a forum (rather than for example iterating over several forums at once) I feel like it's pretty sane.

With the new gate to limit queries to only event categories, I think it's acceptable to continue this pattern here until we completely rework the event/forum relationships as you've described. Sounds like a great 2024 enhancement :D

2023-01-21 06:47 UTC, challfry commented on Sources/App/Controllers/Structs/ControllerStructs.swift
> +	/// If this forum is for an Event on the schedule, the ID of the event.
Yeah, this looks fine. My worry is that forums are already pretty slow, and they are really prone to joining tons of stuff to your query in order to get everything.

2023-01-21 06:53 UTC, challfry approved these changes
Looks good.

2023-01-21 07:02 UTC, merged