API Docs, Time View Improvements, Settings
jocosocial/swiftarr pull request #117
Opened 2023-01-29 19:13 UTC by cohoe

* Fixes https://github.com/jocosocial/swiftarr/issues/77 by ensuring the "all clients, all features" disable combination actually works. Also render the correct template file.
* Cleanup and unification of cruise date settings. IMO it's desirable to set these in `configure.swift` which still requires a `Setting`. We can still use the convenience function for ensuring we get the correct date as coded. But it took me a few different places to find which one actually set the date and that bothered me.
* Set cruise start date and dayofweek for 2023.
* Remove a bunch of useless code in `configure.swift`.
* Unify the swift runtime hostname parameter to `SWIFTARR_IP` which is what the container expects and what is in the example env files. Apparently I missed that we used two different vars for the same function.
* Improve the UX for the time zone check page with the new timezone features.
* Catch up on API change documentation since November.

2023-01-30 23:15 UTC, challfry requested changes

2023-01-30 23:15 UTC, challfry commented on Sources/App/Helpers/Settings.swift
> +	@SettingsValue var cruiseStartDateComponents: DateComponents = DateComponents(year: 1970, month: 1, day: 1)
I'm generally in favor of settings having reasonable default values where possible.

2023-01-30 23:15 UTC, challfry commented on Sources/App/configure.swift
> +	Settings.shared.portTimeZone = TimeZone(identifier: "America/New_York")!
So, if configure.swift isn't relying on any configuration info to set these values, why not just make them the Settings defaults? Settings.swift is where people look first and also where contextual-based "see definition" commands go; the utility of overriding these values in Configure.swift is that Configure gets to look at ... everything and Settings doesn't (or at least: shouldn't).

2023-01-30 23:24 UTC, cohoe commented on Sources/App/Helpers/DisabledSectionMiddleware.swift
> +		if features[.all]?.contains(featureToCheck) ?? false || features[.swiftarr]?.contains(featureToCheck) ?? false || features[.all]?.contains(.all) ?? false {
You're right. Fixed

2023-01-30 23:25 UTC, cohoe commented on Sources/App/Helpers/DisabledSectionMiddleware.swift
> -			return try await request.view.render("featureDisabled.leaf", ctx).encodeResponse(for: request)
Makes sense. I have the same battle with Ansible and Jinja template files. I wish there was a better way to "merge" syntax highlighting of two languages in one file like that.

2023-01-30 23:26 UTC, cohoe commented on Sources/App/Helpers/Settings.swift
> +	@SettingsValue var cruiseStartDateComponents: DateComponents = DateComponents(year: 1970, month: 1, day: 1)
Howsabout we default to something resembling `DateComponents(.today)` instead?

2023-01-30 23:28 UTC, cohoe commented on Sources/App/configure.swift
> +	Settings.shared.portTimeZone = TimeZone(identifier: "America/New_York")!
My goal with doing this is that I intend to make the start date (and a subsequent startdayofweek calculation) come from an environment variable/config file rather than requiring a code change to implement. Doing so would make testing different cases a lot easier. I nearly left a testing date in there until way after I asked for a review last night because I didn't catch that I had "temporarily" changed it on my desktop.

2023-01-30 23:30 UTC, cohoe commented on Sources/App/configure.swift
> +	Settings.shared.portTimeZone = TimeZone(identifier: "America/New_York")!
I forgot to actually document that intention anywhere, so I've opened https://github.com/jocosocial/swiftarr/issues/118 for it.

2023-01-30 23:58 UTC, cohoe commented on Sources/App/Helpers/Settings.swift
> +	@SettingsValue var cruiseStartDateComponents: DateComponents = DateComponents(year: 1970, month: 1, day: 1)
I took a leap and implemented the `.today` as `Calendar(identifier: .gregorian).dateComponents([.year, .month, .day], from: Date())`. Which is 1) gross 2) leads to some weird cases when interacting with the `cruiseStartDayOfWeek` below. I'm fine setting a sane default here but with the caveat that it should be overridable via `configure.swift` for reasons discussed elsewhere.

2023-01-31 03:12 UTC, challfry commented on Sources/App/configure.swift
> +	Settings.shared.portTimeZone = TimeZone(identifier: "America/New_York")!
In general, I'd like it if we could keep it so that a developer new to the project could get up and running with the server with as little configuration work as possible. That's where the 'set reasonable defaults' is coming from.

2023-01-31 03:13 UTC, challfry approved these changes

2023-01-31 03:32 UTC, cohoe commented on Sources/App/configure.swift
> +	Settings.shared.portTimeZone = TimeZone(identifier: "America/New_York")!
:+1: Totally reasonable.

2023-01-31 03:32 UTC, merged