WIP: Seamail Search
jocosocial/swiftarr pull request #131
Opened 2023-02-13 05:41 UTC by hendricksond

2023-02-17 18:46 UTC, cohoe requested changes
One comment re: verbiage on search results.

2023-02-17 18:46 UTC, cohoe commented on Sources/App/Resources/Views/Fez/seamailsearch.html
> +							<li class="list-group-item">You haven't received any Seamail messages yet, but you can create one by tapping "New Seamail"</li>
I think this should say something akin to "No seamail search results found. Start a new seamail by tapping "New Seamail". Otherwise I tested this out on my deployment and it looks great!

2023-02-17 19:21 UTC, hendricksond commented on Sources/App/Resources/Views/Fez/seamailsearch.html
> +							<li class="list-group-item">You haven't received any Seamail messages yet, but you can create one by tapping "New Seamail"</li>
The site wasn't actually using the `seamailSearch` template - it was using the base `seamails` template. So, `seamailSearch` template has been removed, and I've made the "no seamail" message on the template dependent on the route.

2023-02-17 19:55 UTC, cohoe approved these changes
:shipit:

2023-02-17 20:03 UTC, hendricksond commented
Will wait on approval from @challf before merging.

2023-02-17 20:05 UTC, hendricksond commented
TODO: Verify pagination links work correctly.

2023-02-17 23:26 UTC, challfry commented
I haven't tested this, but it looks like the API will return results for LFG messages that match the search parameters unless you exclude them from the results with the type/excludetype query params. It'd only return them for LFGs that you've joined, and the SiteSeamailController does add the query params. I'm guessing that for LFGs you've joined this code also enables search. It's only 'open' LFGs that need more code.

2023-02-17 23:28 UTC, challfry approved these changes
Looks good.

2023-02-19 05:50 UTC, hendricksond commented
@challfry with my latest commit, this search does in fact work for LFGs in the API layer. But, there is a caveat: if there's a LFG where it has `fezpost` records, all of which have been soft-deleted, it will not show in the search results. This is because the soft delete checks are in the `where` clause, instead of in the `left join` clause.

2023-02-19 05:55 UTC, merged