All instances of 'fez' have been renamed to 'chatgroup'.
jocosocial/swiftarr pull request #228
Opened 2023-10-21 19:07 UTC by amytant

Let's get rid of problematic terminology!

API changelist was updated, not sure if that's desirable or not.

And of course, this involves a rename of the /api/v3/fez/ route endpoints, so that needs to be taken into account for clients using the swiftarr API.

2023-10-21 23:18 UTC, cohoe commented
Two main notes:
* We should not have `FriendlyChatGroup`'s. These should just be `ChatGroups`.
* We should not retroactively change the API Changelist. Appending a new item akin to "We renamed Fez to ChatGroup" would be more appropriate.

2023-10-21 23:18 UTC, cohoe requested changes
* We should not have `FriendlyChatGroup`'s. These should just be `ChatGroups`.
* We should not retroactively change the API Changelist. Appending a new item akin to "We renamed Fez to ChatGroup" would be more appropriate.

2023-10-22 01:43 UTC, amytant commented
@cohoe Agreed on both accounts, was doubting about them myself. Changes have been committed.

2023-10-24 05:13 UTC, hendricksond requested changes
I haven't fully gone through this, but I do see some issues:

1. Some instances where it used to be `FriendlyFez` do not have proper casing in the rename. I see a bunch that are `chatgroup` instead of `ChatGroup` - for example, `chatgroupEdit` should probably be `ChatGroupEdit`.
2. A couple filenames still have `Friendly` in them. For example, `Sources/App/Models/FriendlyChatGroup.swift`

2023-10-24 05:13 UTC, hendricksond commented on .jazzy.yaml
> +    - chatgroupEdit
```suggestion
    - ChatGroupEdit
```

2023-10-24 05:13 UTC, hendricksond commented on .jazzy.yaml
> +      - CreatechatgroupEditSchema
```suggestion
      - CreateChatGroupEditSchema
```

2023-10-24 05:13 UTC, hendricksond commented on .jazzy.yaml
> +      - CreatechatgroupSchema
```suggestion
      - CreateChatGroupSchema
```

2023-10-24 05:13 UTC, hendricksond commented on .jazzy.yaml
> +      - SitechatgroupController
```suggestion
      - SiteChatGroupController
```

2023-10-24 11:37 UTC, amytant commented
> I haven't fully gone through this, but I do see some issues:
> 
> 1. Some instances where it used to be `FriendlyFez` do not have proper casing in the rename. I see a bunch that are `chatgroup` instead of `ChatGroup` - for example, `chatgroupEdit` should probably be `ChatGroupEdit`.
> 2. A couple filenames still have `Friendly` in them. For example, `Sources/App/Models/FriendlyChatGroup.swift`

1. Yep, I had a suspicion that might've happened, was a bit too uncautious with a few of those search/replaces. Will fix.
2. Ah, I didn't think about removing `Friendly `from the filenames. Will fix as well.

2025-02-07 05:40 UTC, cohoe commented
Discussed with Amy, gonna close this due to rebasing challenges

2025-02-07 05:40 UTC, closed without merging