Micro karaoke additions
jocosocial/swiftarr pull request #263
Opened 2024-02-24 00:09 UTC by challfry

Micro Karaoke lets users upload mp4 movie files of themselves singing short bits of a song, and then later download all the video pieces to assemble a music video. Swiftarr controls creation of songs (the playlist), dispensing offers to record parts of songs (effectively reservations for song slots), uploading video files, producing manifests of all the files need to assemble to make a song video, notifying users of completed songs, and content moderation.

API changes include:
 - new structs only used by Micro Karaoke
 - a new field in the Global Notification struct,
 - a new App Feature enum case,
 - new notification type; users get notified when a song they contributed to is ready for viewing.
 - new Report types (both Songs and Song Snippets are Reportable content),
 - new User Role, Micro Karaoke Ambassador. Ambassadors aren't limited to one slot per song; intent is that they go around getting others to sing using their phone.

This PR includes all of the song data files, which are mostly organized into numbered folders. There's a lot of them. Generally, for every folder there's a "listen.mp3" file which is a 3-10 sec song clip with vocals, a "record.mp3" file which is karaoke backing audio for the same portion of the song, and a "lyrics.txt" file which is the lyric being sung in the "listen" file.

2024-02-24 18:01 UTC, cohoe requested changes

2024-02-27 01:56 UTC, challfry commented on Package.resolved
> +        "revision" : "291438696abdd48d2a83b52465c176efbd94512b",
Okay, removed.

2024-02-27 01:57 UTC, challfry commented on Sources/swiftarr/Controllers/MicroKaraokeController.swift
> +		let modAuthGroup = addTokenCacheAuthGroup(to: baseRoute).grouped([RequireModeratorMiddleware()])
Okay.

2024-02-27 02:15 UTC, challfry commented on Sources/swiftarr/Controllers/MicroKaraokeController.swift
> +		guard dataSize > 500000 && dataSize < 40 * 1000000 else {
Probably not worth it currently. Unlike image uploads, we've got tight control on where the video upload *should* be coming from. Since we allow users to upload any random image they have, our checks are geared towards keeping the server safe from whatever users upload. For MicroKaraoke, the only valid uploads should come from the Kraken, and those uploads should all be 4-20MB. The check is there to catch people using curl, basically.

2024-02-27 02:19 UTC, challfry commented on Sources/swiftarr/Controllers/MicroKaraokeController.swift
> +		let snippetURL = try getUserUploadedClipsDir().appendingPathComponent(offer.requireID().uuidString).appendingPathExtension("mp4")
Hmm. The MIME type of the upload data is "application/json", because the video data and the offer ID are JSON encoded. Also, Kraken manually sets the mime type; it's not like browser uploads where the browser examines the file being uploaded and tries to intuit the best mime type value.

2024-02-27 08:22 UTC, challfry commented on Sources/swiftarr/Controllers/Structs/ControllerStructs.swift
> +	/// An optional preferred pronoun or form of address.
Yeah, looks like.

2024-02-27 09:05 UTC, challfry commented on Sources/swiftarr/Controllers/MicroKaraokeController.swift
> +		let krakenUserID = req.userCache.getUser(username: "kraken")?.userID ?? UUID()
Done.

2024-02-27 10:39 UTC, challfry commented on Sources/swiftarr/Resources/Assets/microkaraoke/Code Monkey/0/listen.mp3
Okay. Added repo "microkaraoke_songs", and added the microkaraoke dir to .gitignore.

2024-02-27 20:38 UTC, challfry commented on Sources/swiftarr/Controllers/MicroKaraokeController.swift
> +		let snippetURL = try getUserUploadedClipsDir().appendingPathComponent(offer.requireID().uuidString).appendingPathExtension("mp4")
Yeah, that'd require an mp4 parser package on the server. It looks like there's a SwiftFFMpeg package out there, but I'd rather not add it just to validate a file type. Maybe next year we can use SwiftFFMpeg to do server-side video compositing.

Currently a non-mp4 file that gets uploaded is just going to make Kraken fail during the video composition step. We could then check each video on the moderation panel and delete the broken one.

2024-02-27 20:47 UTC, cohoe approved these changes

2024-02-27 21:27 UTC, merged