Personal Events
jocosocial/swiftarr pull request #311
Opened 2024-08-23 01:54 UTC by cohoe

2024-08-23 03:06 UTC, hendricksond requested changes
So far, all I've looked at is the database stuff. Definitely open to discussion if you don't want to make these changes.

2024-08-23 03:06 UTC, hendricksond commented on Sources/swiftarr/Migrations/Schema Creation/PersonalEventSearchIndexCreation.swift
> +struct CreatePersonalEventSearchIndexes: AsyncMigration {
Since this is a brand new table, you could do this inside `struct CreatePersonalEventSchema: AsyncMigration`

2024-08-23 03:06 UTC, hendricksond commented on Sources/swiftarr/Models/PersonalEvent.swift
> +			.field("participant_array", .array(of: .uuid), .required)
Should we use a pivot instead of an array on the event? Query performance might be better.

2024-08-23 03:19 UTC, cohoe commented on Sources/swiftarr/Models/PersonalEvent.swift
> +			.field("participant_array", .array(of: .uuid), .required)
My first iteration did that. So far the only cases where I've wanted to expand more than just the array of UUIDs I was able to use the `UserCache` which comes from Redis/memory. No extra database-ing required! So I left it as the `[UUID]` instead.

2024-08-23 03:26 UTC, hendricksond commented on Sources/swiftarr/Models/PersonalEvent.swift
> +			.field("participant_array", .array(of: .uuid), .required)
Okay, great! Caching! Haven't gotten to that part yet 🤣

2024-08-24 03:54 UTC, cohoe commented on Sources/swiftarr/Migrations/Schema Creation/PersonalEventSearchIndexCreation.swift
> +struct CreatePersonalEventSearchIndexes: AsyncMigration {
Have you done this somewhere before? I did a quick check and there are some type casting differences between `Database` and `SQLDatabase` that would make the regular migration a bit more complicated (or at least look and feel different than other migrations we do).

2024-08-30 00:32 UTC, challfry commented
I feel the web UI should really have a way to view a user's personal events, and likely a form to create new ones. Especially since without this, a native app user could create an event, invite users who are web-only, and the web users would have no way of accessing the event.

There was a conversation about this back in the Twitarr 2.0 days, the idea was that the web UI would always be feature-complete (relative to the available API features) from both a user and moderator perspective, while other clients could pick and choose as needed. This isn't quite the case anymore, but that's mostly for technical reasons. Micro Karaoke doesn't display completed videos using the web UI because it does not have them, you can't record MK clips from the web UI because I have no idea how to do that (mostly the real-time audio filtering), and the telephone feature doesn't work because it seems really hard to do on the web.

Anyway, none of that's the case here. Showing the personal events a user is scheduled for is doable and provides value to users.

2024-08-30 00:33 UTC, challfry requested changes

2024-08-30 00:33 UTC, challfry commented on Sources/swiftarr/Resources/Views/User/userFavorites.html
> +#endextend
I kind of feel this page ought to have a form that lets the user find new users to favorite; basically a copy and paste of 'Find Twitarr Users' except the action button is 'favorite' instead of 'view'.

2024-08-30 00:33 UTC, challfry commented on Sources/swiftarr/Site/SiteUserController.swift
> +			throw "Invalid username parameter"
Technically it's a userID parameter.

2024-08-30 00:33 UTC, challfry commented on Sources/swiftarr/Site/SiteUserController.swift
> +			throw "Invalid username parameter"
Okay, that 'userID parameter' thing is really picky. Nobody who gets this error is actually going to be confused about it.

2024-08-31 03:23 UTC, cohoe commented on Sources/swiftarr/Controllers/ModerationController.swift
> +		moderatorAuthGroup.get("personalevent", personalEventIDParam, use: personalEventModerationHandler)
That is intentional. The only reason Personal Events are mod-able in the first place is because the owner can invite other users. And even though the invitees are users who have already favorited the owner, the possibility of something bad happening still exists.

I do not want mods to have the ability to potentially delete items from users private data. Only in the event of an incident. The intended flow is that if a friend reports another friend, the reporting friend can be removed from the event by mods. If an escalation is needed that should result in an action against the owning user, not their event.

2024-08-31 03:24 UTC, cohoe commented on Sources/swiftarr/Helpers/ICSHelper.swift
> +				UID:\(icsEscapeString(event.personalEventID.uuidString))
To clarify: would you rather the UID field get populated with a different UUID or other value than the PE ID?

2024-08-31 03:25 UTC, cohoe commented on Sources/swiftarr/Site/SiteUserController.swift
> +			throw "Invalid username parameter"
I copy pasta'd this from another function. In general should we be doing that in the site ui?

2024-08-31 03:37 UTC, challfry commented on Sources/swiftarr/Helpers/ICSHelper.swift
> +				UID:\(icsEscapeString(event.personalEventID.uuidString))
A different UUID is fine, in fact the same UUID as the database ID is fine. The issue is that I think Fluent can have models that autogenerate primary keys, or models that require the user to set the primary key before calling create(), but not both in the same table. And, if you're want user-generated keys, you need to use `@id(custom: "id_field", generatedBy: .user)` in your field declaration. 

The only effect of all this is that a user that made a personal event on the pre-reg server, exported the event to their calendar app, and then re-exported once on the boat would get their events doubled up, as they'd have different UIDs. Having a separate UID field lets you retain the value if the event moves from one server to another.

2024-08-31 03:44 UTC, challfry commented on Sources/swiftarr/Controllers/ModerationController.swift
> +		moderatorAuthGroup.get("personalevent", personalEventIDParam, use: personalEventModerationHandler)
I suppose the thing I was really thinking about was mods being able to lock an event so the owner couldn't just keep re-adding the reporting user. This is only an issue because it can take some time for THO to step in and drop the ban hammer.

2024-08-31 03:51 UTC, challfry commented on Sources/swiftarr/Site/SiteUserController.swift
> +			throw "Invalid username parameter"
Yep, the "Mutes the given user ID" comment out front shoulda told me.

2024-08-31 04:02 UTC, challfry commented on Sources/swiftarr/Site/SiteUserController.swift
> +			throw "Invalid username parameter"
Wait. I think I get what you're asking. My philosophy is that site UI should be validating its own requirements are met, which in this case means checking it's called with an actual UUID. It still lets the API determine whether there's a user with that UUID, because that's an API-level job.

2024-08-31 07:23 UTC, challfry commented on Sources/swiftarr/Controllers/ModerationController.swift
> +		moderatorAuthGroup.get("personalevent", personalEventIDParam, use: personalEventModerationHandler)
Oh. I forgot--the reporting user can just un-friend the event owner if they're getting spam-reinvited. Never mind; closing this.

2024-09-01 01:22 UTC, cohoe commented on Sources/swiftarr/Migrations/Schema Creation/PersonalEventSearchIndexCreation.swift
> +struct CreatePersonalEventSearchIndexes: AsyncMigration {
Clever. Implemented.

2024-09-01 02:10 UTC, cohoe commented on Sources/swiftarr/Controllers/Structs/ControllerStructs.swift
> +	var personalEventID: UUID
Comments added. Implemented the startTime-endTime restriction and backported to LFG as well. I know we don't have export functions for those, but actually that could be useful too some day. Added an API level block to prevent favoriting yourself.

2024-09-01 03:01 UTC, cohoe commented on Sources/swiftarr/Helpers/ICSHelper.swift
> +				UID:\(icsEscapeString(event.personalEventID.uuidString))
Good point. I've refactored to make the `UID` a SHA256 hash of the `startTime` and `title`. Hopefully that is unique enough to solve the pre-reg server case. I thought about using the `stampTime` but I'm not convinced that would work since it's a Fluent-managed field.

2024-09-01 03:03 UTC, hendricksond commented on Sources/swiftarr/Helpers/ICSHelper.swift
> +				UID:\(icsEscapeString(event.personalEventID.uuidString))
Is title editable? If yes, that could cause trouble.

2024-09-01 03:03 UTC, cohoe commented on Sources/swiftarr/Controllers/PersonalEventController.swift
> +		let favoritesUserIDs = favorites.map({ $0.$user.id })
Oooo I like that. I'll take my points now.

2024-09-01 03:07 UTC, cohoe commented on Sources/swiftarr/Helpers/ICSHelper.swift
> +				UID:\(icsEscapeString(event.personalEventID.uuidString))
Hmm, yes it is.

2024-09-03 01:56 UTC, cohoe commented on Sources/swiftarr/Resources/Views/User/userFavorites.html
> +#endextend
Looking into this, we use an HTML `<template>` for the user search results. https://github.com/jocosocial/swiftarr/blob/76371a6a127042b6ba648ceb89e61fa29e2721df/Sources/swiftarr/Resources/Views/User/directory.html#L34-L46

There is a CSS selector class `.append-userid-to-href` that uses JS to shove the resulting `userID` onto the `href` property of that tag.

https://github.com/jocosocial/swiftarr/blob/76371a6a127042b6ba648ceb89e61fa29e2721df/Sources/swiftarr/Resources/Assets/js/swiftarr.js#L666-L669

Favoriting, like other relations (Block, Mute), uses a data toggle action pattern with completely different elements. https://github.com/cohoe/swiftarr/blob/e0f586b59eb20c05cb7dada451666e558b9d922c/Sources/swiftarr/Resources/Views/User/userProfile.html#L81-L86

All this to say, while I like the idea, I don't love what it would take to implement. I can slap the user search in there but IMO it looks a little crowded.

2024-09-03 02:01 UTC, cohoe commented
> I feel the web UI should really have a way to view a user's personal events, and likely a form to create new ones. Especially since without this, a native app user could create an event, invite users who are web-only, and the web users would have no way of accessing the event.
> 
> There was a conversation about this back in the Twitarr 2.0 days, the idea was that the web UI would always be feature-complete (relative to the available API features) from both a user and moderator perspective, while other clients could pick and choose as needed. This isn't quite the case anymore, but that's mostly for technical reasons. Micro Karaoke doesn't display completed videos using the web UI because it does not have them, you can't record MK clips from the web UI because I have no idea how to do that (mostly the real-time audio filtering), and the telephone feature doesn't work because it seems really hard to do on the web.
> 
> Anyway, none of that's the case here. Showing the personal events a user is scheduled for is doable and provides value to users.

I agree. My intention is to do a somewhat major overhaul of the "Events" section of the Site UI. In Tricordarr I've made a distinction of "Schedule" == show whats happening, object types `Event`, `PersonalEvent`, and optionally `Fez`. Mostly to disambiguate the coding structures for "Event" and "PersonalEvent" and "Fez". Anywho, I don't want to wrap this refactor into this PR because 1) it's gonna be really big and difficult to separate from the underlying personal event code and 2) I plan to work on it later.

2024-10-02 21:45 UTC, challfry approved these changes
Okay. There's still no UI for the web client to show users their personal events, but let's get this merged in so it's done.

2024-10-02 23:14 UTC, merged