Forum sort direction
jocosocial/swiftarr pull request #320
Opened 2024-10-03 04:31 UTC by hendricksond

Add optional parameter `order` to forum queries. Supported values are `ascending, descending`.

Closes #317

2024-10-07 00:36 UTC, challfry requested changes
Looks good in general; only requesting one change.

2024-10-07 00:36 UTC, challfry commented on Sources/swiftarr/Helpers/CryptoHelper.swift
> +import Crypto
I wish there were better resources to see the state of what libraries are available on which platforms; currently there's a few Apple libraries that have 'official' cross-platform availability (the swift-foundation stuff), and a bunch of projects to make an open-source shadow of an Apple-only library. Since there's a bunch of devs (like me) that develop on on Mac and generally know a bunch of the available APIs, it's a dumb guessing game to figure out which of them will compile for Linux.

2024-10-07 04:50 UTC, hendricksond commented on Sources/swiftarr/Extensions/Fluent+Extensions.swift
> +	func sortDir(_ req: Request, _ defaultOrder: DatabaseQuery.Sort.Direction) -> DatabaseQuery.Sort.Direction {
I like this suggestion. It does mean `Vapor+Extensions` needs to `import FluentSQL`, but that shouldn't be a problem. Will have the changes in shortly!

2024-10-07 21:29 UTC, cohoe approved these changes

2024-10-08 04:23 UTC, challfry approved these changes
Looks good.

2024-10-08 05:15 UTC, merged