Personal Events UI
jocosocial/swiftarr pull request #327
Opened 2024-11-23 23:36 UTC by challfry

Adds a Day Planner view, which shows followed Events, LFGs the user has created or joined, and Personal Events the user has created or been invited to. Also has UI for creating Personal Events, updating them, adding/removing members, and chat. 

Personal Events are now a new type of LFG. The methods in PersonalEventController mostly call through to FezController. FezController itself now supports two new types; `privateEvent` which allows for user inviting and chat, and `personalEvent` which is solely for the creating user.

Adds a 'Former' tab to the LFG panel, showing the user Seamails, LFGs, and Private Events they were previously members of and letting them file reports without being members.

2024-11-24 14:27 UTC, challfry commented
Oh. This PR will fix #322.

2024-11-25 04:16 UTC, cohoe requested changes
How should we handle notification socket events for `.personalEvent` type LFG chat messages? Currently we have different types for "fez" and "seamail" which clients can use to infer a route to direct the action of the event. For example, pressing the notification in Tricordarr will take you to its internal `/lfg/:fezID` route versus `/seamail/:fezID`. I think we should do something similar by creating a `.privateEventUnreadMsg` type in SocketStructs and the other place that I am forgetting right now.

https://github.com/jocosocial/swiftarr/blob/master/Sources/swiftarr/Controllers/Structs/SocketStructs.swift#L80-L83

That planner view is great! I also like the noun "planner" for this thing. In Tricordarr I called it "Schedule" to disambiguate between Events, PersonalEvents, and LFGs. But I like Planner better and am going to adopt that there too.

2024-11-25 04:16 UTC, cohoe commented on Sources/swiftarr/Extensions/Foundation+Extensions.swift
> +extension Bool: @retroactive RESPValueConvertible {
What does `@retroactive` achieve here?

2024-12-03 23:32 UTC, challfry commented on Sources/swiftarr/Extensions/Foundation+Extensions.swift
> +extension Bool: @retroactive RESPValueConvertible {
It's a new-ish Swift thing. [swift-evolution proposal](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0364-retroactive-conformance-warning.md)

RESPValueConvertable is a RediStack protocol that means "things that can be converted into something Redis can store". Currently, the RediStack module doesn't add Bool conformance to RESPValueConvertable, although all the numeric types are there as well as various collection types. So I added the conformance (a while ago) because I needed it. But, Swiftarr (the module) doesn't own the protocol (RESPValueConvertable, owned by RediStack) nor the conforming type (Bool, owned by Foundation, I guess?). If Redis were to add this same conformance in the future the compiler would be at a loss as to which conformance's code to use. @retroactive partially solves this by saying "If the module containing either the protocol or the type also includes this conformance, use their implementation and not ours".

Swift 6 gives warning about this.

2024-12-03 23:34 UTC, challfry commented
Okay. The notification structs now have new fields to cover Personal Event notifications, as well as some other new stuff I threw in.

2024-12-04 02:31 UTC, cohoe approved these changes

2024-12-04 22:08 UTC, merged