Redis Data Consistency Job
jocosocial/swiftarr pull request #347
Opened 2024-12-21 05:33 UTC by cohoe

2025-01-07 03:43 UTC, challfry requested changes

2025-01-07 03:43 UTC, challfry commented on Sources/swiftarr/Site/Utilities/NotificationsMiddleware.swift
> +				if lastCheckDate.timeIntervalSinceNow > -60.0 && Settings.shared.enableSiteNotificationDataCaching {
Hmm. Generally, the 60 second refresh should be a backstop for the Redis `UsersWithNotificationStateChange` set. Whenever there's a change to notification data for a user, the API layer should add that user to the set by calling `reds.addUsersWithStateChange()`. `addNotifications()`, `subtractNotifications()` and `markNotificationsViewed()` all call this.

2025-01-07 03:43 UTC, challfry commented on Sources/swiftarr/Protocols/APICollection.swift
> +		return (event.startTime, id)
Okay. I think we want to be calling `addUsersWithStateChange()` here. Doing so causes NotificationMiddleware to reload the user's notification data the next time a page is loaded on site.

2025-01-07 03:43 UTC, challfry commented on Sources/swiftarr/Protocols/APICollection.swift
> +		return (event.startTime, id)
I might be able to decouple `addNotifications()` from Request. Hmm.

2025-01-07 03:46 UTC, cohoe commented on Sources/swiftarr/Protocols/APICollection.swift
> +		return (event.startTime, id)
I got a few levels in, hit the `UserCache`, and got scared of threads.

2025-01-08 01:11 UTC, cohoe commented on Sources/swiftarr/Protocols/APICollection.swift
> +		return (event.startTime, id)
Good call on `addUsersWithStateChange()`. I have added this.

2025-01-08 01:12 UTC, cohoe commented on Sources/swiftarr/Site/Utilities/NotificationsMiddleware.swift
> +				if lastCheckDate.timeIntervalSinceNow > -60.0 && Settings.shared.enableSiteNotificationDataCaching {
I improved the behavior of the Chat participant processing to better be able to call `addUsersWithStateChange()` without adding the entire set of users. Will also log/warn when inconsistencies are found which may aid us in figuring out where they are coming from.

2025-01-13 06:03 UTC, challfry approved these changes
Looks good.

2025-01-13 06:05 UTC, merged